[package]
name = "rspacp"
version = "0.1.0"
authors = ["CityBear3"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.27.2"
env_logger = "*"
log ="0.4.14"